### ISSUE TITLE
Move from ESMA_cmake to f2py-cmake

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/QFED#19]
Per @amdasilva, QFED (and GMAOpyobs) are pure Python compare to a lot of GEOS-ESM packages. As such, they really have no need for ESMA_cmake or ecbuild, say. However, they do use f2py a lot and our f2py CMake code is in ESMA_cmake. 

But, @amdasilva pointed me to [`f2py-cmake`](https://github.com/scikit-build/f2py-cmake) by @henryiii.

I have a first rough version of the transition in the [`feature/mathomp4/plume-no-esma`](https://github.com/GEOS-ESM/QFED/tree/feature/mathomp4/plume-no-esma) branch (which is [based off of `feature/#17/adasilva/plume_rise`](https://github.com/GEOS-ESM/QFED/compare/feature/%2317/adasilva/plume_rise...feature/mathomp4/plume-no-esma))

ETA: NOTE: The `f2py-cmake` code in my branch is a modified version of the stock code, see https://github.com/scikit-build/f2py-cmake/issues/21 where we have some fixes to allow it to be run more than once.

**Comment by mathomp4** [comment]
As noted by @amdasilva when he tested this, this does *build* but it doesn't run.

For example:
```
> python3 -c 'import FreitasPlume_'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /gpfsm/dswdev/mathomp4/Models/QFED-Arlindo-f2pycmake/install/lib/Python/plumerise/FreitasPlume_.cpython-311-x86_64-linux-gnu.so: undefined symbol: plume_
```
and the same for `LockePlume_`:

```
> python3 -c 'import LockePlume_'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /gpfsm/dswdev/mathomp4/Models/QFED-Arlindo-f2pycmake/install/lib/Python/plumerise/LockePlume_.cpython-311-x86_64-linux-gnu.so: undefined symbol: plumeg_
```

**Comment by mathomp4** [comment]
I thought I had one fix which is that `UseF2Py.cmake` does not realize that our `.F90` files are Fortran 90. The code has:
```cmake
    foreach(file IN LISTS ALL_FILES)
        if("${file}" MATCHES "\\.f90$")
            set(HAS_F90_FILE TRUE)
            break()
        endif()
    endforeach()
```
this is simple enough to fix by adding a:
```cmake
        if("${file}" MATCHES "\\.F90$")
            set(HAS_F90_FILE TRUE)
            break()
        endif()
```
in there. 

But this doesn't seem to do much.

**Comment by mathomp4** [comment]
One more thing I notice is that the f2pywrapper files are empty:
```
> \ls -l *wrap*
-rw-r--r-- 1 mathomp4 g0620 0 Dec 17 09:14 FreitasPlume_-f2pywrappers.f
-rw-r--r-- 1 mathomp4 g0620 0 Dec 17 09:14 FreitasPlume_-f2pywrappers2.f90
-rw-r--r-- 1 mathomp4 g0620 0 Dec 17 09:14 LockePlume_-f2pywrappers.f
-rw-r--r-- 1 mathomp4 g0620 0 Dec 17 09:14 LockePlume_-f2pywrappers2.f90
```

So it's almost like the code isn't actually doing what I think it should. My call sequence is pretty boring:
```cmake
# Library: plumerise
# ------------------
add_library (plumerise
  LockePlume_Mod.F90
  rconstants.F90
  FreitasPlume_Mod.F90
  qsat_Mod.F90
)
install(TARGETS plumerise DESTINATION lib/Python/plumerise)

# Module: FreitasPlume
# --------------------
f2py_object_library(FreitasPlume_object OBJECT)
f2py_generate_module(FreitasPlume_ FreitasPlume_py.F90 OUTPUT_VARIABLE FreitasPlume_files)
python_add_library(FreitasPlume_ MODULE "${FreitasPlume_files}" WITH_SOABI)
target_link_libraries(FreitasPlume_ PRIVATE Python::NumPy)
target_link_libraries(FreitasPlume_ PRIVATE FreitasPlume_object)
target_link_libraries(FreitasPlume_ PRIVATE plumerise)
target_link_libraries(FreitasPlume_ PRIVATE OpenMP::OpenMP_Fortran)
install(TARGETS FreitasPlume_ DESTINATION lib/Python/plumerise)
```
